package com.example.jobfinderapp.activities;
import android.app.DatePickerDialog;import android.content.Intent;import android.os.Bundle;import android.text.TextUtils;import android.view.View;import android.widget.ArrayAdapter;import android.widget.AutoCompleteTextView;import android.widget.Toast;import androidx.appcompat.app.AppCompatActivity;import com.example.jobfinderapp.R;import com.example.jobfinderapp.database.DBHelper;import com.example.jobfinderapp.models.Category;import com.example.jobfinderapp.models.Company;import com.example.jobfinderapp.models.Job;import com.example.jobfinderapp.models.User;import com.example.jobfinderapp.utils.UserSession;import com.google.android.material.appbar.MaterialToolbar;import com.google.android.material.button.MaterialButton;import com.google.android.material.textfield.TextInputEditText;import java.text.ParseException;import java.text.SimpleDateFormat;import java.util.*;
public class AddJobActivity extends AppCompatActivity{
 private TextInputEditText title,salary,location,desc,req,deadline,exp,edu,qty,age;private AutoCompleteTextView category,type,gender;private MaterialButton save;private DBHelper db;private int companyId=-1,jobId=-1,selected=-1;private List<Category> cats;private boolean saving;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_add_job);db=DBHelper.getInstance(this);jobId=getIntent().getIntExtra("JOB_ID",-1);UserSession s=new UserSession(this);int uid=s.isLoggedIn()?s.getUserId():-1;User u=uid>0?db.getUserById(uid):null;Company c=uid>0?db.getCompanyByUserId(uid):null;if(u==null||!DBHelper.ROLE_EMPLOYER.equals(u.getRole())||!DBHelper.STATUS_ACTIVE.equals(u.getStatus())){s.clear();goLogin();return;}if(c==null||TextUtils.isEmpty(c.getName())||TextUtils.isEmpty(c.getAddress())||TextUtils.isEmpty(c.getDescription())){Toast.makeText(this,"Vui lòng hoàn thiện hồ sơ công ty trước",Toast.LENGTH_LONG).show();startActivity(new Intent(this,CompanyProfileActivity.class));finish();return;}companyId=c.getId();init();loadCategories();setupDate();if(jobId>0)loadJob();save.setOnClickListener(v->submit());}
 private void init(){title=findViewById(R.id.etJobTitle);salary=findViewById(R.id.etSalary);location=findViewById(R.id.etLocation);desc=findViewById(R.id.etDescription);req=findViewById(R.id.etRequirement);deadline=findViewById(R.id.etDeadline);exp=findViewById(R.id.etExperience);edu=findViewById(R.id.etEducation);qty=findViewById(R.id.etQuantity);age=findViewById(R.id.etAge);category=findViewById(R.id.spinnerCategory);type=findViewById(R.id.spinnerJobType);gender=findViewById(R.id.spinnerGender);save=findViewById(R.id.btnSaveJob);MaterialToolbar t=findViewById(R.id.toolbar);t.setNavigationOnClickListener(v->finish());String[] types={"Toàn thời gian","Bán thời gian","Thực tập","Làm việc từ xa","Hợp đồng"};type.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_dropdown_item_1line,types));String[] genders={"Không yêu cầu","Nam","Nữ"};gender.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_dropdown_item_1line,genders));}
 private void loadCategories(){cats=db.getAllCategories();List<String> names=new ArrayList<>();for(Category c:cats)names.add(c.getName());category.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_dropdown_item_1line,names));category.setOnItemClickListener((p,v,pos,id)->selected=cats.get(pos).getId());save.setEnabled(!cats.isEmpty());if(cats.isEmpty())Toast.makeText(this,"Chưa có danh mục việc làm",Toast.LENGTH_LONG).show();}
 private void setupDate(){deadline.setFocusable(false);deadline.setOnClickListener(v->{Calendar c=Calendar.getInstance();new DatePickerDialog(this,(x,y,m,d)->deadline.setText(String.format(Locale.ROOT,"%02d/%02d/%04d",d,m+1,y)),c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show();});}
 private void loadJob(){Job j=db.getJobById(jobId);if(j==null||j.getCompanyId()!=companyId){Toast.makeText(this,"Tin tuyển dụng không hợp lệ",Toast.LENGTH_SHORT).show();finish();return;}title.setText(j.getTitle());salary.setText(j.getSalary());location.setText(j.getLocation());desc.setText(j.getDescription());req.setText(j.getRequirement());deadline.setText(j.getDeadline());exp.setText(j.getExperience());edu.setText(j.getEducation());qty.setText(String.valueOf(j.getQuantity()));age.setText(j.getAge());type.setText(j.getJobType(),false);gender.setText(j.getGender(),false);selected=j.getCategoryId();for(Category c:cats)if(c.getId()==selected)category.setText(c.getName(),false);}
 private void submit(){if(saving)return;String t=title.getText().toString().trim(),sa=salary.getText().toString().trim(),lo=location.getText().toString().trim(),de=desc.getText().toString().trim(),re=req.getText().toString().trim(),dl=deadline.getText().toString().trim(),q=qty.getText().toString().trim();if(t.isEmpty()){title.setError("Nhập tiêu đề");title.requestFocus();return;}if(selected<0){category.setError("Chọn danh mục");category.requestFocus();return;}if(sa.isEmpty()){salary.setError("Nhập mức lương");salary.requestFocus();return;}if(lo.isEmpty()){location.setError("Nhập địa điểm");location.requestFocus();return;}if(de.isEmpty()){desc.setError("Nhập mô tả công việc");desc.requestFocus();return;}if(re.isEmpty()){req.setError("Nhập yêu cầu ứng viên");req.requestFocus();return;}int n;try{n=Integer.parseInt(q);}catch(Exception e){qty.setError("Số lượng phải là số nguyên dương");qty.requestFocus();return;}if(n<=0||n>10000){qty.setError("Số lượng không hợp lệ");return;}if(!validDate(dl)){deadline.setError("Hạn nộp không hợp lệ hoặc đã qua");return;}Job j=new Job();j.setId(jobId);j.setCompanyId(companyId);j.setCategoryId(selected);j.setTitle(t);j.setSalary(sa);j.setLocation(lo);j.setDescription(de);j.setRequirement(re);j.setDeadline(dl);j.setExperience(exp.getText().toString().trim());j.setEducation(edu.getText().toString().trim());j.setQuantity(n);j.setAge(age.getText().toString().trim());j.setJobType(type.getText().toString().trim());j.setGender(gender.getText().toString().trim());saving=true;save.setEnabled(false);boolean ok=jobId>0?db.updateJob(j):db.addJob(j);if(ok){setResult(RESULT_OK);Toast.makeText(this,jobId>0?"Đã cập nhật tin":"Đã đăng tin tuyển dụng",Toast.LENGTH_SHORT).show();finish();}else{saving=false;save.setEnabled(true);Toast.makeText(this,"Không thể lưu tin tuyển dụng",Toast.LENGTH_LONG).show();}}
 private boolean validDate(String s){try{Date d=new SimpleDateFormat("dd/MM/yyyy",Locale.ROOT).parse(s);Calendar today=Calendar.getInstance();today.set(Calendar.HOUR_OF_DAY,0);today.set(Calendar.MINUTE,0);today.set(Calendar.SECOND,0);today.set(Calendar.MILLISECOND,0);return d!=null&&!d.before(today.getTime());}catch(ParseException e){return false;}}
 private void goLogin(){Intent i=new Intent(this,LoginActivity.class);i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK);startActivity(i);finish();}
}
