package com.example.jobfinderapp.activities;
import android.app.AlertDialog; import android.content.Intent; import android.os.Bundle; import android.view.View; import android.widget.Toast; import androidx.appcompat.app.AppCompatActivity; import androidx.recyclerview.widget.LinearLayoutManager; import androidx.recyclerview.widget.RecyclerView; import com.example.jobfinderapp.R; import com.example.jobfinderapp.adapters.PendingEmployerAdapter; import com.example.jobfinderapp.database.DBHelper; import com.example.jobfinderapp.models.User; import com.example.jobfinderapp.utils.UserSession; import java.util.ArrayList; import java.util.List; import java.util.Map;
public class PendingEmployerActivity extends AppCompatActivity {
 private DBHelper db; private List<Map<String,Object>> rows=new ArrayList<>(); private PendingEmployerAdapter adapter;
 @Override public void onCreate(Bundle b){super.onCreate(b);db=DBHelper.getInstance(this);UserSession s=new UserSession(this);User u=s.isLoggedIn()?db.getUserById(s.getUserId()):null;if(u==null||!DBHelper.ROLE_ADMIN.equals(u.getRole())||!DBHelper.STATUS_ACTIVE.equals(u.getStatus())){s.clear();toLogin();return;}setContentView(R.layout.activity_pending_employer);RecyclerView rv=findViewById(R.id.rvPendingEmployers);rv.setLayoutManager(new LinearLayoutManager(this));adapter=new PendingEmployerAdapter(rows,(row,approve)->confirm(row,approve));rv.setAdapter(adapter);findViewById(R.id.btnBack).setOnClickListener(v->finish());load();}
 private void load(){rows.clear();rows.addAll(db.getPendingEmployers());adapter.notifyDataSetChanged();findViewById(R.id.tvEmpty).setVisibility(rows.isEmpty()?View.VISIBLE:View.GONE);}
 private void confirm(Map<String,Object> row,boolean approve){String status=approve?DBHelper.STATUS_ACTIVE:DBHelper.STATUS_REJECTED;new AlertDialog.Builder(this).setTitle(approve?"Duyệt nhà tuyển dụng":"Từ chối nhà tuyển dụng").setMessage("Bạn có chắc chắn không?").setPositiveButton("Xác nhận",(d,w)->{if(db.updateEmployerStatus(Integer.parseInt(String.valueOf(row.get("user_id"))),status)){load();Toast.makeText(this,"Đã cập nhật trạng thái",Toast.LENGTH_SHORT).show();}}).setNegativeButton("Hủy",null).show();}
 private void toLogin(){Intent i=new Intent(this,LoginActivity.class);i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK);startActivity(i);finish();}
}
